contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('<int:contact_id>/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),

    # path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    # user
    path('user/register/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

# abrir imagem no navegador
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/forms.py
# importa forms
from django import forms
from django.contrib.auth import password_validation
# criar usuarios
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from . import models

# class do user admin
class RegisterForm(UserCreationForm):
        
        # colocando restrições nos campos
        first_name = forms.CharField(
             required=True,
             min_length=3,
        )

        last_name = forms.CharField(
             required=True,
             min_length=3,
        )

        email = forms.EmailField(
             required=True,
             min_length=3,
        )

        class Meta:
          model = User
          fields = (
               'first_name', 'last_name', 'email',
               'username', 'password1', 'password2'
          )

        # verifica se ja existe um email no banco de dados
        def clean_email(self):
            email = self.cleaned_data.get('email')
            
            if User.objects.filter(email=email).exists():
                 self.add_error(
                      'email',
                      ValidationError('Já existe este e-mail', code='invalid')
                 )
            
            return email
     

# class altera os campos do formulario
class ContactForm(forms.ModelForm):

    # mudando o input first_name, label do form
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'classe-a classe-b',
                'placeholder': 'Aqui veio do init',
            }
        ),
        label='Primeiro Nome',
        help_text='Texto de ajuda para seu usuário',
    )

    # alterando campo do last_name
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'classe-a classe-b',
                'placeholder': 'Aqui veio do init',
            }
        ),
        label='Último Nome',
        help_text='Texto de ajuda para seu usuário',
    )

    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'classe-a classe-b',
                'placeholder': 'Aqui veio do init',
            }
        ),
        label='Telefone',
        help_text='Texto de ajuda para seu usuário',
    )


    # mudando o input da imagem
    picture = forms.ImageField(
         widget=forms.FileInput(
              attrs={
                   'accept': 'image/*'
              }
         ),
         required=False
    )

    # não sabe o que vai receber
    # outra forma de mudar type dos inputs 
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

        # self.fields['first_name'].widget.attrs.update({
        #     'class': 'classe-a classe-b',
        #     'placeholder': 'Aqui veio do init',
        # })

    class Meta:
        model = models.Contact

        # cria os campos na view de acordo com o model
        fields = (
            'first_name', 'last_name', 'phone', 'email', 'description', 'category', 'picture'
        )

        # troca o type do input; passwordInput
        # widgets = {
        #     'first_name': forms.TextInput(
        #         attrs={
        #             'class': 'classe-a classe-b',
        #             'placeholder': 'Escreva aqui',
        #         }
        #     )
        # }

    # mensagens de erro 
    def clean(self):
        cleaned_data = self.cleaned_data
        # self.add_error(
        #     'first_name',
        #     ValidationError(
        #         'Mensagem de erro',
        #         code='invalid'
        #     )
        # )
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
                # self.add_error(
                #     'first_name',
                msg = ValidationError(
                    'Primeiro nome nãp pode ser igual ao ultimo nome',
                    code='invalid'
                )
                #)
                
                self.add_error('first_name', msg)
                self.add_error('last_name', msg)
        
        return super().clean()
    
    # validando um campo em especifico
    # clean_ mais o nome do campo
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':

            # raise: para o código
            # raise ValidationError(
            #     'Não digite ABC',
            #     code = 'invalid'
            # )

            self.add_error(
                'first_name',
                ValidationError(
                    'Não digite ABC',
                    code = 'invalid'
                )
            )
        
        return first_name
    

# atualiza o usuario
class RegisterUpdateForm(forms.ModelForm):
     
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
          model = User
          fields = (
               'first_name', 'last_name', 'email', 'username'
          )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)

        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):

        # pega as senha do formulario
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):

        # email quem vem do form
        email = self.cleaned_data.get('email')

        # email atual do usuario logado
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )

        return email
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

contact/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(
        request,
        'contact/index.html',
    )

contact/views/contact_forms.py
# from django.shortcuts import render, redirect
from contact.models import Contact
from django.shortcuts import render, redirect, get_object_or_404
from contact.forms import ContactForm
from contact.models import Contact
from django.contrib.auth.decorators import login_required

# muda dinamicamente uma url
from django.urls import reverse

# https://docs.djangoproject.com/en/4.2/topics/pagination/
from django.core.paginator import Paginator

# Create your views here.
@login_required(login_url='contact:login')
def create(request):

    form_action = reverse('contact:create')
    

    # se o formulario é enviado 
    # formulario enviado
    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES)
        context = {
            'form': form,
            'form_action': form_action,
            'titulo_view': 'Criar novo contato'
        }

        if form.is_valid():
            # contact = form.save(commit=False)
            # contact.show = False
            # contact.save()


            contact = form.save(commit=False)

            # coloca o owner em quem cria o contato
            contact.owner = request.user
            contact.save()

            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )
    # fim do envio do formulario
  
    # leva para a view o ContactForm com os inputs
    context = {
        'form': ContactForm(),
        'form_action': form_action,
        'titulo_view': 'Criar novo contato'
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def update(request, contact_id):

    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )

    form_action = reverse('contact:update', args=(contact_id,))

    # se o formulario é enviado 
    # formulario enviado
    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES, instance=contact)
        context = {
            'form': form,
            'form_action': form_action,
            'titulo_view': 'Atualizar contato'
        }

        if form.is_valid():
            # contact = form.save(commit=False)
            # contact.show = False
            # contact.save()
            contact = form.save()

            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )
    # fim do envio do formulario
  
    # leva para a view o ContactForm com os inputs
    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
        'titulo_view': 'Atualizar contato'
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')


    #contact.delete()
    #return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation
        }
    )

contact/views/contact_views.py
from django.shortcuts import render, redirect
from contact.models import Contact
from django.shortcuts import get_object_or_404, render
from django .db.models import Q

# https://docs.djangoproject.com/en/4.2/topics/pagination/
from django.core.paginator import Paginator

# Create your views here.

def index(request):
    contacts = Contact.objects.all().filter(show=True).order_by('-id')

    # mostra a query
    # print(contacts.query)

    paginator = Paginator(contacts, 10)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }

    return render(
        request,
        'contact/index.html',
        context
    )

def contact(request, contact_id):

    #single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(
        Contact, pk=contact_id, show=True
        )

    # mostra a query
    # print(contacts.query)
    contact_name = f'{single_contact.first_name} {single_contact.last_name}'

    context = {
        'contact': single_contact,
        'site_title': contact_name
    }

    return render(
        request,
        'contact/contact.html',
        context
    )

def search(request):

    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')


    # filtro
    contacts = Contact.objects.all().filter(show=True).filter(Q(first_name__icontains=search_value) | Q(last_name__icontains=search_value)).order_by('-id')

    paginator = Paginator(contacts, 10)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    # mostra a query
    # print(contacts.query)

    #envia os dados para view 
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - ',
        'search_value': search_value
    }

    # renderiza a view
    return render(
        request,
        'contact/index.html',
        context
    )

contact/views/user_forms.py
from django.shortcuts import render, redirect

# imorta as classes de contact/form.py
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib import messages, auth
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required


# formulário de registro
def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()

            # mensagens 
            messages.info(request, 'Um texto')
            # messages.success(request, 'Um texto')
            # messages.warning(request, 'Um texto')
            # messages.error(request, 'Um texto')

            return redirect('contact:index')

    return render(
        request,
        'contact/register.html',
        {
            'form': form
        }
    )

# renderiza a tela de login
def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():

            user = form.get_user()

            # faz o login do usuario
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso')
            return redirect('contact:index')
        messages.error(request, 'Login inválido')

    return render(
        request,
        'contact/login.html',
        {
            'form':form
        }
    )


# faz logout
@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')


# decora login
@login_required(login_url='contact:login')
def user_update(request):

    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )
    
    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )
    
    form.save()
    return redirect('contact:user_update')

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}

<div class="single-contact">
    <h1 class="single-contact-name">
        {{ contact.firtst_name }}
        {{ contact.last_name }}
    </h1>
    <p>
        id: {{ contact.id }}
    </p>
    <p>
        e-mail: {{ contact.email }}
    </p>
    <p>
        id: {{ contact.category.name }}
    </p>

    {% if contact.picture %}
    <p>
        <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }}">
    </p>
    {% endif %}


    {% if user == contact.owner %}
        <div class='contact-links'>
            <a class='btn btn-link' href="{% url 'contact:update' contact.id %}">Alterar</a>
            
            <form method="POST" action="{% url 'contact:delete' contact.id %}">
                {% csrf_token %}

                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes">
                    <button class="btn btn-delete" type="submit">Confirma?</button>
                {% else %}
                    <button class="btn btn-delete" type="submit">Deletar</button>
                {% endif %}
            </form>
        </div>
    {% endif %}
    
</div>

{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
  <h1>{{ titulo_view }}</h1>
  <div class="form-wrapper">

    <h2>Contact</h2>

    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >

    {% csrf_token %}

      <div class="form-content">

        <!-- gera os campos inputs pelo field  -->
        {% for field in form  %}
            <div class="form-group">
                <label for="{{field.id_for_label}}">{{ field.label }}</label>
                <!-- input -->
                {{ field }}

                <!-- erros -->
                {{ field.errors }}
                
                <p class="help-text">
                  {{ field.help_text }}
                 </p> 
            </div>
        {% endfor %}

        <!-- mensagens de erros -->
        {% if form.non_field_errors %}
            <div class='form-content' >
                <div class='form-group'>

                  <div class="message error">
                    {{form.non_field_errors}}
                  </div>

                </div>
            </div>
        {% endif %}

        
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>

  {% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}

    {% if page_obj %}
        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contatos
                </caption>
                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">
                            ID
                        </th>
                        <th class="table-header">
                            Nome
                        </th>
                        <th class="table-header">
                            Sobrenome
                        </th>
                        <th class="table-header">
                            Telefone
                        </th>
                        <th class="table-header">
                            E-mail
                        </th>
                    </tr>
                    <tbody>
                        {% for contact in page_obj %}
                            <tr class="table-cel">
                                <td class="table-cel">
                                    <a href="{% url 'contact:contact' contact.id %}" class="table-link">
                                        {{contact.id}}
                                    </a>
                                </td>
                            
                                <td class="table-cel">
                                    {{contact.first_name}}
                                </td>
                        
                                <td class="table-cel">
                                    {{contact.last_name}}
                                </td>
                            
                                <td class="table-cel">
                                    {{contact.phone}}
                                </td>
                        
                                <td class="table-cel">
                                    {{contact.email}}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </thead>
            </table>
        </div>
    {% else %}
        <div class="single-contact">
            <h1 class="single-contact-name">
                Nenhum contato encontrado    
            <h1>
        </div>
    {% endif %}

{% endblock content %}

contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
  <h1>{{ titulo_view }}</h1>
  <div class="form-wrapper">

    <h2>Login {{ user }} {{user.is_authenticated}}</h2>

    {% if user.is_authenticated %}
        <p>Você esta logo, para sair clique <a href="{%url 'contact:logout'%}">aqui</a> </p>

    {% else %}
        <p>VocÊ não esta logado</p>
        {% include 'contact/partials/user_form.html' %}
    {% endif %}

    
    
  </div>

  {% endblock content %}

contact/templates/contact/register.html
{% extends 'global/base.html' %}

{% block content %}
  <h1>{{ titulo_view }}</h1>
  <div class="form-wrapper">

    <h2>Registrar</h2>

    {% include 'contact/partials/user_form.html' %}
    
  </div>

  {% endblock content %}

contact/templates/contact/user_update.html
{% extends 'global/base.html' %}

{% block content %}
  <h1>{{ titulo_view }}</h1>
  <div class="form-wrapper">

    <h2>Atualizar perfil</h2>

    {% include 'contact/partials/user_form.html' %}
    
  </div>

  {% endblock content %}